export const ROUTES = {
  dashboard: '/(tabs)/dashboard',
  stock: '/(tabs)/stock',
  bill: '/(tabs)/bill',
  customers: '/(tabs)/customers',
  more: '/(tabs)/more',
  purchase: '/purchase',
  purchaseHistory: '/purchase-history',
  stockHistory: '/stock-history',
  bills: '/bills',
  customerLedger: '/customer-ledger',
  customerForm: '/customer-form',
  collections: '/collections',
  transport: '/transport',
  expenses: '/expenses',
  reports: '/reports',
  settings: '/settings',
} as const;
